/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.pages;

import main.PageManager;
import main.audio.AudioManager;
import main.database.DataManager;

import java.awt.Color;
import java.awt.Dimension;
import java.util.ArrayList;

/**
 *
 * @author raffo
 */
public class PaginaSelezioneSala extends Page {
    private ArrayList<TemplateElementoDx> templatesDx;
    private ArrayList<TemplateElementoSx> templatesSx;
    private int width;
    private int height;
    
    /**
     * Creates new form PaginaSelezioneSala
     */
    public PaginaSelezioneSala() {
        super("SelectionRooms");
        templatesDx = new ArrayList<>();
        templatesDx.add(new TemplateElementoDx("Sala Paleozoica"));
        templatesDx.add(new TemplateElementoDx("Sala Cenozoica"));
        templatesDx.add(new TemplateElementoDx("Sala Mesozoica"));
        templatesSx = new ArrayList<>();
        templatesSx.add(new TemplateElementoSx("Sala Neoarcheana"));
        templatesSx.add(new TemplateElementoSx("Sala Paleoprotozoica"));
        templatesSx.add(new TemplateElementoSx("Sala Mesoprotozoica"));
        width = 1250;
        height = 253 * (templatesDx.size() + templatesSx.size());
        setPreferredSize(new Dimension(width, height));
        setMinimumSize(new Dimension(width, height));
        setMaximumSize(new Dimension(width, height));
        for(int i = 0; i < templatesDx.size() + templatesSx.size(); i++){
            if(i % 2 == 0){
                templatesDx.get(i/2).setLocation(0, i * 253);
                templatesDx.get(i/2).setSize(1250, 250);
                this.add(templatesDx.get(i/2));
            }
            else{
                templatesSx.get(i/2).setLocation(0, i * 253);
                templatesSx.get(i/2).setSize(1250, 250);
                this.add(templatesSx.get(i/2));
            }
        }
        initComponents();
    }
    
    public int getWidth(){
        return width;
    }
    
    public int getHeight(){
        return height;
    }

    @Override
    public void initPage(AudioManager audioManager, PageManager pageManager, DataManager dataManager) {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(50, 50, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1250, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
