/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.pages;

import main.PageManager;
import main.audio.AudioManager;
import main.database.*;
import main.events.SelectionMouseManager;

import javax.swing.*;
import java.awt.*;
import java.io.IOException;
import java.util.HashMap;

/**
 * Classe che rappresenta un elemento selezionabile
 * @author Simone Raffo
 */
public class TemplateElementoDx extends Page {

    private int codice;
    private int backCodice;
    private String typeSelection;

    /**
     * Creates new form TemplateElementoDx
     */
    public TemplateElementoDx(String typeSelection, int codice, int backCodice) {
        super("templateElemDx");
        initComponents();
        this.codice = codice;
        this.typeSelection = typeSelection;
        this.backCodice = backCodice;
    }

    @Override
    public void initPage(AudioManager audioManager, PageManager pageManager, DataManager dataManager) {
        switch(typeSelection) {
            case "room":
                this.initRoom(audioManager, pageManager, dataManager);
                break;
            case "find":
                this.initFind(audioManager, pageManager, dataManager);
                break;
            case "case":
                this.initCase(audioManager, pageManager, dataManager);
                break;
        }
    }

    private void initRoom(AudioManager audioManager, PageManager pageManager, DataManager dataManager) {
        HashMap<String, String> params = new HashMap<>();
        params.put("type", "sala");
        params.put("codice", "" + codice);
        Room room;
        try {
            room = dataManager.requestData(Room.class, params);
        } catch (IOException e) {
            e.printStackTrace();
            return;
        }

        try {
            Image img = dataManager.requestImage(room.getPlanimetria());
            img = new ImageIcon(img).getImage().getScaledInstance(344, 198, Image.SCALE_SMOOTH);
            immagineElemento.setIcon(new ImageIcon(img));
        } catch (IOException e) {
            return;
        }

        params = new HashMap<>();
        params.put("type", "periodoStorico");
        params.put("codice", "" + room.getPeriodoStorico());
        HistoricalPeriod period;
        try {
            period = dataManager.requestData(HistoricalPeriod.class, params);
        } catch (IOException e) {
            e.printStackTrace();
            return;
        }

        this.addMouseListener(new SelectionMouseManager(audioManager, pageManager, codice, "case", backCodice));
        titoloElemento.setText("Sala periodo " + period.getNome());
    }

    private void initCase(AudioManager audioManager, PageManager pageManager, DataManager dataManager) {
        HashMap<String, String> params = new HashMap<>();
        params.put("type", "teca");
        params.put("codice", "" + codice);
        Teca teca;
        try {
            teca = dataManager.requestData(Teca.class, params);
        } catch (IOException e) {
            e.printStackTrace();
            return;
        }

        //TODO:foto teca

        this.addMouseListener(new SelectionMouseManager(audioManager, pageManager, codice, "find", backCodice));
        titoloElemento.setText("Teca " + teca.getCodice());
        descrizione.setText(teca.getDescrizione());
    }

    private void initFind(AudioManager audioManager, PageManager pageManager, DataManager dataManager) {
        HashMap<String, String> params = new HashMap<>();
        params.put("type", "reperto");
        params.put("codice", "" + codice);
        Reperto find;
        try {
            find = dataManager.requestData(Reperto.class, params);
        } catch (IOException e) {
            e.printStackTrace();
            return;
        }

        try {
            Image img = dataManager.requestImage(find.getFotoURL());
            img = new ImageIcon(img).getImage().getScaledInstance(344, 198, Image.SCALE_SMOOTH);
            immagineElemento.setIcon(new ImageIcon(img));
        } catch (IOException e) {
            return;
        }

        params = new HashMap<>();
        params.put("type", "specie");
        params.put("codice", "" + find.getSpecie());
        Specie specie;
        try {
            specie = dataManager.requestData(Specie.class, params);
        } catch (IOException e) {
            e.printStackTrace();
            return;
        }

        this.addMouseListener(new SelectionMouseManager(audioManager, pageManager, codice, "selectFind", backCodice));
        titoloElemento.setText(specie.getNome());
        descrizione.setText(find.getDescrizione());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenitoreImmagine = new javax.swing.JPanel();
        immagineElemento = new javax.swing.JLabel();
        pannelloDescrizione = new javax.swing.JPanel();
        contenitoreDescrizione = new javax.swing.JScrollPane();
        descrizione = new javax.swing.JTextArea();
        titoloElemento = new javax.swing.JLabel();

        setBackground(new java.awt.Color(199, 190, 169));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMaximumSize(new java.awt.Dimension(1250, 32767));
        setPreferredSize(new java.awt.Dimension(1250, 250));

        contenitoreImmagine.setBackground(new java.awt.Color(60, 53, 57));

        immagineElemento.setBackground(new java.awt.Color(60, 53, 57));

        javax.swing.GroupLayout contenitoreImmagineLayout = new javax.swing.GroupLayout(contenitoreImmagine);
        contenitoreImmagine.setLayout(contenitoreImmagineLayout);
        contenitoreImmagineLayout.setHorizontalGroup(
                contenitoreImmagineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 356, Short.MAX_VALUE)
                        .addGroup(contenitoreImmagineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(contenitoreImmagineLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(immagineElemento, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                                        .addContainerGap()))
        );
        contenitoreImmagineLayout.setVerticalGroup(
                contenitoreImmagineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 210, Short.MAX_VALUE)
                        .addGroup(contenitoreImmagineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenitoreImmagineLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(immagineElemento, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                        .addContainerGap()))
        );

        pannelloDescrizione.setBackground(new java.awt.Color(60, 53, 57));
        pannelloDescrizione.setPreferredSize(new java.awt.Dimension(484, 210));

        contenitoreDescrizione.setBorder(null);

        descrizione.setEditable(false);
        descrizione.setBackground(new java.awt.Color(60, 53, 57));
        descrizione.setColumns(20);
        descrizione.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        descrizione.setForeground(new java.awt.Color(255, 255, 255));
        descrizione.setLineWrap(true);
        descrizione.setRows(5);
        descrizione.setText("Morbi a mauris pulvinar, euismod quam eget, tempor ex. Nullam ");
        descrizione.setWrapStyleWord(true);
        descrizione.setBorder(null);
        descrizione.setFocusable(false);
        contenitoreDescrizione.setViewportView(descrizione);

        titoloElemento.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        titoloElemento.setForeground(new java.awt.Color(255, 255, 255));
        titoloElemento.setText("Sala Cretaceo");

        javax.swing.GroupLayout pannelloDescrizioneLayout = new javax.swing.GroupLayout(pannelloDescrizione);
        pannelloDescrizione.setLayout(pannelloDescrizioneLayout);
        pannelloDescrizioneLayout.setHorizontalGroup(
                pannelloDescrizioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pannelloDescrizioneLayout.createSequentialGroup()
                                .addContainerGap(12, Short.MAX_VALUE)
                                .addGroup(pannelloDescrizioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(titoloElemento, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(contenitoreDescrizione, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15))
        );
        pannelloDescrizioneLayout.setVerticalGroup(
                pannelloDescrizioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pannelloDescrizioneLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(titoloElemento, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(contenitoreDescrizione, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(pannelloDescrizione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(388, 388, 388)
                                .addComponent(contenitoreImmagine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(contenitoreImmagine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pannelloDescrizione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane contenitoreDescrizione;
    private javax.swing.JPanel contenitoreImmagine;
    private javax.swing.JTextArea descrizione;
    private javax.swing.JLabel immagineElemento;
    private javax.swing.JPanel pannelloDescrizione;
    private javax.swing.JLabel titoloElemento;
    // End of variables declaration//GEN-END:variables
}
